### ISSUE TITLE
skidded

### ISSUE THREAD

**Issue by ghost** [Aran404/Member-Booster#1]
skidded from https://github.com/b6m/DiscordTokenGen

**Comment by Aran404** [comment]
Yes totally skib

**Comment by Tukz1** [comment]
> skidded from https://github.com/b6m/DiscordTokenGen

https://github.com/xtekky/Discord-Token-Gen *

**Comment by Aran404** [comment]
Tukz shush

**Comment by oaoaoaoaoaoaoaoaoa** [comment]
> Tukz shush

😞

**Comment by oaoaoaoaoaoaoaoaoa** [comment]
> Tukz shush

monkey

**Comment by ghost** [comment]
> > skidded from https://github.com/b6m/DiscordTokenGen
> 
> https://github.com/xtekky/Discord-Token-Gen *

ur a skib
